name: pre-commit

on:
  push:
    branches: [ main, master, dev ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: configure
      run: |
        cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DUSE_CPM=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - uses: pre-commit/action@v2.0.0
